#!/bin/bash
# Quick Help - Heatmap Optimization Commands
# ===========================================

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                    🔥 HEATMAP OPTIMIZATION SYSTEM                          ║"
echo "║                          Quick Reference Guide                             ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 DOCUMENTATION:"
echo "  • HEATMAP_OPTIMIZATION_GUIDE.md     - Full guide (333 lines)"
echo "  • HEATMAP_SYSTEM_RESUMEN.md         - Executive summary"
echo "  • SISTEMA_HEATMAPS_INSTALADO.txt    - Installation checklist"
echo ""
echo "🚀 QUICK START:"
echo "  1. Setup (once):        ./setup_heatmap_optimization.sh"
echo "  2. Quick test:          python test_heatmap_optimization.py"
echo "  3. Full optimization:   python optimize_with_heatmaps.py --trials 100"
echo ""
echo "🔍 ANALYZE RESULTS:"
echo "  • View top configs:     python inspect_optimization_results.py --top 10"
echo "  • Compare w/ current:   python inspect_optimization_results.py --compare"
echo "  • Generate dashboard:   python generate_optimization_summary.py"
echo ""
echo "🎯 FOCUSED ANALYSIS:"
echo "  • Risk sizing:          python analyze_parameter_ranges.py --analysis risk"
echo "  • Filter strictness:    python analyze_parameter_ranges.py --analysis filters"
echo "  • RVOL impact:          python analyze_parameter_ranges.py --analysis rvol"
echo "  • Boolean switches:     python analyze_parameter_ranges.py --analysis switches"
echo "  • All of above:         python analyze_parameter_ranges.py --analysis all"
echo ""
echo "✅ APPLY RESULTS:"
echo "  • Generate config:      python apply_optimized_params.py"
echo "  • View config:          cat config/optimized_defaults.py"
echo "  • Edit Streamlit:       # Import OPTIMIZED_DEFAULTS in app.py"
echo ""
echo "🔧 COMMON OPTIONS:"
echo "  --trials N              Number of optimization trials (default: 100)"
echo "  --limit N               Max tickers to test (default: 50)"
echo "  --start YYYY-MM-DD      Start date (default: 2021-01-01)"
echo "  --end YYYY-MM-DD        End date (default: 2021-12-31)"
echo ""
echo "📊 EXPECTED OUTPUTS (outputs/optimization/):"
echo "  ⭐⭐⭐⭐⭐ risk_parameters_heatmap.html"
echo "  ⭐⭐⭐⭐⭐ categorical_analysis.html"
echo "  ⭐⭐⭐⭐⭐ parameter_importance.html"
echo "  ⭐⭐⭐⭐   filter_strictness_heatmap.html"
echo "  + 6 more HTML files + CSV + JSON"
echo ""
echo "💡 TIPS:"
echo "  • Start with quick test (10 min) before full optimization (1-2 hours)"
echo "  • Look for green zones in heatmaps (high Profit Factor)"
echo "  • Validate out-of-sample after applying optimized config"
echo "  • Expected improvement: +25-45% in Profit Factor"
echo ""
echo "🆘 HELP:"
echo "  • Full guide:           cat HEATMAP_OPTIMIZATION_GUIDE.md | less"
echo "  • Quick summary:        cat SISTEMA_HEATMAPS_INSTALADO.txt"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
